language: java

services:
  - docker

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    # via the "travis encrypt" command using the project repo's public key
    # encypted for db/$project
    - secure: "OkxYzZFNWv3LY7UxkKC6ll6F3SxA2ma1Sf8cN8/dcIDZCGXPgbxVsSLYqVWaxkSfswiKtA035RGqyugOMND1iBg+5nmoubJMykfKyBzEVmUgBPwZznCAE9F472u0nV9r4YCXyvI4rrHDUDCNMi1GFrSfi4GL9R2aCdjLEDOHDl/oaRT9uNtk2h+941bt3RRtgih8lwS8P0Ug9FuRCEYyhQY1OjtYPnJ4tuODr8cN1qp8cimXVwqSnPRkMg+a7sa/h32dFQ9g9k5IWiSA83fol4ajZ6+b9q+LxtmujlMZqx3FEzSASqwZl6zWuXs4qBnsnhdTPeU2vvGHVTJW/fmhI/dtb5xRuNsM2KSxl6gy7cavj3i/GWFI8hWkea5nhTMK6ehBOJS52PsGM/bP2uCKHE5BAOvg/KFHILLIrxBmkxnfGQ5ZjWctcFKVYTR4fNkawlCI7f94bnm4l+g+qkLjHOGgs8RMhgKLChn3GyIC/fPJFT1ZUuUICnBIa9iIz/iDlMUBWRj/2wK02hX9OY4Mvroi8ABBHGU3HCdn++pUhKBaQMvRtTlN7AldCuFuNUR+RL5LD5c0qTV+9a+VfVdg2BQ8SCD3enOIt2tY394p0U3jWAIHpS0pzxfeOqXztpqMgWFbvVnzYHYc+64q9IOf1vxeJpqo189nmSZcnTn3yLo="

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
  - sudo apt-get install jq
  - curl https://raw.githubusercontent.com/hmcts/reform-api-docs/master/bin/publish-swagger-docs.sh > publish-swagger-docs.sh
  - echo -n | openssl s_client -connect scan.coverity.com:443 2>./openssl-connect.stderr | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
  - if [[ ${TRAVIS_BRANCH} == 'coverity_scan' ]]; then git remote add upstream https://github.com/hmcts/$(echo ${TRAVIS_REPO_SLUG} | cut -d "/" -f2).git; git remote -v; fi
  - if [[ ${TRAVIS_BRANCH} == 'coverity_scan' ]]; then git fetch upstream master; fi
  - if [[ ${TRAVIS_BRANCH} == 'coverity_scan' ]]; then git log -1 --pretty=format:%H upstream/master; fi
  - if [[ ${TRAVIS_BRANCH} == 'coverity_scan' ]]; then git rebase upstream/master; fi

script:
  - if [[ ${COVERITY_SCAN_BRANCH} == 1 ]];
    then
        echo "Don't build on coverty_scan branch.";
        exit 0;
    fi
  - ./gradlew check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew installDist bootRepackage
  - test "$TRAVIS_BRANCH" = "master" && test "$TRAVIS_PULL_REQUEST" = "false" && sh ./publish-swagger-docs.sh

addons:
  coverity_scan:
    project:
      name: "dwaynebailey/document-management-store-app"
      description: "Document Store"
    notification_email: Dwayne.Bailey@HMCTS.net
    build_command: ./gradlew build
    branch_pattern: coverity_scan
